{$NO_AUTO_EXECUTE}
UseUpdatedEma( true );
EnableSynch( false );

//______________________________________________________________________________


//______________________________________________________________________________
//______________________________________________________________________________
// Main Program
var lib: ComVariant;
//lib := CreateOleObject( 'WLExtra.Utility' );
lib := CreateOleObject( 'WealthLab.WL3' );






